### ISSUE TITLE
Hello, I would like to ask how to download this data?

### ISSUE THREAD

**Issue by gyc666** [IS2AI/Kazakh_ASR#1]
Hello, I would like to ask how to download this data? Is there a charge for it, but can I download it for free for research purposes?

**Comment by mussakhojayeva** [comment]
Hi! I fixed the README.
Please fill this form https://docs.google.com/forms/d/e/1FAIpQLSf_usCjxTvbH_2xhA6slH9FAfjrYVd4OHnr-CUcVVW3TEAscg/viewform and you will receive a link for download.
