### ISSUE TITLE
Some incorrect results on sample wav file

### ISSUE THREAD

**Issue by ardakshalkar** [IS2AI/Kazakh_ASR#2]
```
ardak@Ardak:~/Kazakh_ASR$ python3 recognize.py --wav_path 19mar2019lastaddress_00000.wav
recognize.py --wav_path 19mar2019lastaddress_00000.wav
Namespace(wav_path='19mar2019lastaddress_00000.wav')
time passed: 74.60966241
RECOGNIZED жарнама саламатсыздар ма саламатсыздар ма саламатсыздар ма
```
I used this wav file: [Kaggle Nazarbayev Speech Dataset](https://storage.googleapis.com/kagglesdsdata/datasets/2749228/4751796/dataset/wavs/19mar2019lastaddress_00000.wav?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=databundle-worker-v2%40kaggle-161607.iam.gserviceaccount.com%2F20230222%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230222T085644Z&X-Goog-Expires=345600&X-Goog-SignedHeaders=host&X-Goog-Signature=7f2b0d3def239a69fcfa40b24a80dbdf4efea1e0a4a0e4e09a539ad404c42e44c34d660b3cbcbeba30b071d7c332cf51ba058c54a72149058c803eec49f3001dff748ebaa99c90474ef5a68d1e79a19c791e489ecaaf0fe4f37eb83cae89e4dd773e002ba0c90a810e1121448f7be4c68225b0e210887703ed3de17b9255500a12b0ff4e833400aa19f73ba4d50715105fded647a023e6ad1ec50dc6529474c65a99a476c0453c05db5bc2565ba67c86ec4ab6713fbbbe46070d21664af50972ec33dd357c4836f2d13a1fd22c070efa8416cf4a82197e2bb7471bc7249443526efa93633340f13ee1cab380d3ca283da1d252f0c2bd5821785613957b43d034)

What can be a problem?

**Comment by mussakhojayeva** [comment]
Hello. Please make sure your wav files are have sample rate of 16k. As I inspected the file you have sent, it is 22k
